INSERT INTO user
(id,
 first_name,
 last_name,
 email,
 password,
 phone_number,
 username,
 picture_id,
 role)
VALUES (1,
        'behnaz',
        'yousefi',
        'b.yousefi2911@gmail.com',
        'admin',
        '989352229966',
        'admin',
        null,
        'ROLE_ADMIN');
INSERT INTO user
(id,
 first_name,
 last_name,
 email,
 password,
 phone_number,
 username,
 picture_id,
 role)
VALUES (2,
        'bahareh',
        'yousefi',
        'behyousefi@yahoo.com',
        'user_test1',
        '989352229977',
        'user_test1',
        null,
        'ROLE_USER');