spring:
  data:
    rest:
      base-path: /api

jwt:
  secret: mybookshop

logging:
  config: src/main/resources/logback.xml
  level:
    org.springframework.data.rest: debug

---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost:3306/db_bookshop
    username: b_yousefi
    password: b_yousefi
    data: classpath:/META-INF/sql/init-1-dbFiles.sql,classpath:/META-INF/sql/init-2-categories.sql,classpath:/META-INF/sql/init-3-publications.sql,classpath:/META-INF/sql/init-4-authors.sql,classpath:/META-INF/sql/init-5-books.sql
    initialization-mode: always
    platform: mysql
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      #for database auto creation
#      ddl-auto : create-drop
    #for database auto creation
    generate-ddl: true


logging:
  config: src/main/resources/logback-prod.xml
  level:
    b_yousefi: WARN

---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa