spring:
  data:
    rest:
      base-path: /api
#  datasource:
#    url: jdbc:mysql://localhost:9090/db_bookshop
#    username: yousefi
#    password: yousefi

jwt:
  secret: mybookshop

logging:
  level:
    org.springframework.data.rest: debug

bookshop:
  books:
    pageSize: 10


  discount:
    codes:
      abcdef: 10

---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost/bookshop
    username: yousefi
    password: yousefi

logging:
  level:
    tacos: WARN
    
