spring:
  data:
    rest:
      base-path: /bookshop/api

jwt:
  secret: mybookshop

logging:
  config: classpath:logback.xml
  level:
    org.springframework.data.rest: debug

springdoc:
  api-docs:
    path: /bookshop/api-docs
  swagger-ui:
    path: /bookshop/api-docs/swagger-ui.html

---
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/db_bookshop
    username: b_yousefi
    password: b_yousefi
    data: classpath:/META-INF/sql/init-1-dbFiles.sql,classpath:/META-INF/sql/init-2-categories.sql,classpath:/META-INF/sql/init-3-publications.sql,classpath:/META-INF/sql/init-4-authors.sql,classpath:/META-INF/sql/init-5-books.sql
    initialization-mode: always
    platform: mysql
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      #for database auto creation
      ddl-auto: create-drop
    show-sql: true
    #for database auto creation
    generate-ddl: true

logging:
  config: classpath:logback-prod.xml
  level:
    b_yousefi: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

server:
  port: 8443
  ssl:
    key-store: classpath:keystore/mykeys.jks
    key-store-password: AAAA
    key-password: AAAA
    keyStoreType: JKS
    keyAlias: tomcat
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://db/db_bookshop
    username: root
    password: mysql
    data: classpath:/META-INF/sql/prod/init-1-dbFiles.sql,classpath:/META-INF/sql/init-2-categories.sql,classpath:/META-INF/sql/init-3-publications.sql,classpath:/META-INF/sql/init-4-authors.sql,classpath:/META-INF/sql/init-5-books.sql
    platform: mysql
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create-drop
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  config: classpath:logback-prod.xml
  level:
    b_yousefi: info
    org.springframework.data.rest: error
